version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: cargo
    directory: /packages/rust
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /packages/python
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
